export const template = [
    {
        id: 1,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'Button not working',
        app: 'DeNetPayments',
        status: 'New',
        created: '01/29/2022',
        severity: 'Critical',
        priority: 'Urgent',
    },
    {
        id: 567,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'App not loading',
        app: 'DeNet Pass',
        status: 'On review',
        created: '01/29/2022',
        severity: 'Medium',
        priority: 'Critical',
    },
    {
        id: 56,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'Not claimed',
        app: 'DeNet Storage',
        status: 'In progress',
        created: '01/29/2022',
        severity: 'Low',
        priority: 'Medium',
    },
    {
        id: 56,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'Not claimed',
        app: 'DeNet Storage',
        status: 'In progress',
        created: '01/29/2022',
        severity: 'Low',
        priority: 'Medium',
    },
    {
        id: 56,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'Not claimed',
        app: 'DeNet Storage',
        status: 'In progress',
        created: '01/29/2022',
        severity: 'Low',
        priority: 'Medium',
    },
    {
        id: 56,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'Not claimed',
        app: 'DeNet Storage',
        status: 'In progress',
        created: '01/29/2022',
        severity: 'Low',
        priority: 'Medium',
    },
    {
        id: 45,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'No award recieved and',
        app: 'DeNet Payments',
        status: 'Rejected',
        created: '01/29/2022',
        severity: 'High',
        priority: 'Instant',
    },
    {
        id: 45,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'No award recieved and',
        app: 'DeNet Payments',
        status: 'Rejected',
        created: '01/29/2022',
        severity: 'High',
        priority: 'Instant',
    },
    {
        id: 45,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'No award recieved and',
        app: 'DeNet Payments',
        status: 'Rejected',
        created: '01/29/2022',
        severity: 'High',
        priority: 'Instant',
    },
    {
        id: 45,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'No award recieved and',
        app: 'DeNet Payments',
        status: 'Rejected',
        created: '01/29/2022',
        severity: 'High',
        priority: 'Instant',
    },
    {
        id: 45,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'No award recieved and',
        app: 'DeNet Payments',
        status: 'Rejected',
        created: '01/29/2022',
        severity: 'High',
        priority: 'Instant',
    },
    {
        id: 234,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'App not loading',
        app: 'DeNet Payments',
        status: 'Solved',
        created: '01/29/2022',
        severity: 'Critical',
        priority: 'Low',
    },
    {
        id: 234,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'App not loading',
        app: 'DeNet Payments',
        status: 'Solved',
        created: '01/29/2022',
        severity: 'Critical',
        priority: 'Low',
    },
    {
        id: 234,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'App not loading',
        app: 'DeNet Payments',
        status: 'Solved',
        created: '01/29/2022',
        severity: 'Critical',
        priority: 'Low',
    },
    {
        id: 234,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'App not loading',
        app: 'DeNet Payments',
        status: 'Solved',
        created: '01/29/2022',
        severity: 'Critical',
        priority: 'Low',
    },
    {
        id: 234,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'App not loading',
        app: 'DeNet Payments',
        status: 'Solved',
        created: '01/29/2022',
        severity: 'Critical',
        priority: 'Low',
    },
    {
        id: 234,
        adress: 'daw8da6fr7esf7sfs',
        bug: 'App not loading',
        app: 'DeNet Payments',
        status: 'Solved',
        created: '01/29/2022',
        severity: 'Critical',
        priority: 'Low',
    }
]